name: Generate javadoc for Robolectric release

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  aggregateDocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # zulu suports complete JDK list
          java-version: 14

      - uses: gradle/gradle-build-action@v2

      - name: Download Robolectric 4.10
        run: git clone --recurse-submodules -b robolectric-4.10-alpha-1 --single-branch https://github.com/robolectric/robolectric.git

      - name: Run aggregateDocs
        run: cd robolectric && SKIP_NATIVERUNTIME_BUILD=true ./gradlew clean aggregateDocs # building the native runtime is not required for checking javadoc

      - uses: actions/upload-artifact@v3
        with:
          name: robolectric-javadoc
          path: |
            robolectric/build/docs/javadoc
            robolectric/build/docs/json
