name: Generate javadoc for Robolectric release

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  aggregateDocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # zulu suports complete JDK list
          java-version: 17

      - uses: gradle/gradle-build-action@v3

      - name: Download Robolectric 4.11.1
        run: git clone -b robolectric-4.11.1 --single-branch https://github.com/robolectric/robolectric.git

      - name: Run aggregateDocs
        run: cd robolectric && ./gradlew clean aggregateDocs

      - uses: actions/upload-artifact@v4
        with:
          name: robolectric-javadoc
          path: |
            robolectric/build/docs/javadoc
            robolectric/build/docs/json
